### ISSUE TITLE
使用remote 模式时，www bundle 有报错，unknown error，换成LoadFromFile，又会报其他，再把路径的file://去掉就能正常了。

### ISSUE THREAD

**Issue by MidiSmallYue** [icipiqkm/QP.Framework#1]

**Comment by icipiqkm** [comment]
嗯，安卓和ios的路径修改一下路径就行了，我修复后会更新的

**Comment by z40144322** [comment]
www bundle换成LoadFromFile 具体是哪个文件哪个方法？
去掉Util.cs里public static string WWWDeviceResPath方法里面Android下的file://也不行。模拟器里面查看文件已经下载，但界面不跳转。也看不到其他错误信息。

使用remote 模式PC上是可以的，android上不行，ios还没有试。

**Comment by MidiSmallYue** [comment]
AssetBundle.LoadFromFile()，我是把bundle  用这个加载了，unity 版本 2018.1，还有 资源下载路径你用的哪个，如果你有服务器的话就是公网IP，电脑web服务器的话,pc 是 127.0.0.1 也行，手机得一个WiFi，局域网ip地址才行。我用的模拟器试的.
