### ISSUE TITLE
构建开始打包报错error CS1061

### ISSUE THREAD

**Issue by z40144322** [icipiqkm/QP.Framework#2]
构建开始打包报错
Assets/XLua/Gen/UnityEngineLightWrap.cs(691,60): error CS1061: Type `UnityEngine.Light' does not contain a definition for `shadowRadius' and no extension method `shadowRadius' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?

Unity版本2018.1.6f1

**Comment by icipiqkm** [comment]
你可以尝试把 new List<string>(){"UnityEngine.Light", "shadowRadius"},按照XLua的说明 加入到黑名单中。
查看XLuaCustomExport.cs 和ExampleGenConfig.cs 有演示怎么加入黑名单

**Comment by z40144322** [comment]
问题已经解决，添加黑名单或者去掉XLua自带的例子文件夹Examples都可以解决
