### ISSUE TITLE
下载后显示  Loading_Main跳转场景失败

### ISSUE THREAD

**Issue by terribleness** [icipiqkm/QP.Framework#5]
LUA: 一切逻辑从这里开始
Loading_Main跳转场景失败

刚下载运行起来

**Comment by icipiqkm** [comment]
修改Assets/Defined/GameConfig.cs 的 gameModel
如果gameModel == Editor 不更新，需要把Modules下面所有场景添加到File->Build Settings中

**Comment by icipiqkm** [comment]
有没有其他报错信息？

**Comment by terribleness** [comment]
Build Settings 中都所有场景都加上就好了
