### ISSUE TITLE
UnauthorizedAccessException:Access to the path "/jar:file" is denied.

### ISSUE THREAD

**Issue by terribleness** [icipiqkm/QP.Framework#6]
打包后Console中显示红色的 UnauthorizedAccessException:Access to the path "/jar:file" is denied.
config配置的local，在真机上打开app，腾讯视频那段播放后，就在Console里面看到报错。

**Comment by icipiqkm** [comment]
真机需要配置Remote ,local和Editor 只适合编辑器

**Comment by terribleness** [comment]
感谢。已解决
我fork后增加FairyGUI，项目中需要。
https://github.com/terribleness/FUL.Framework

**Comment by icipiqkm** [comment]
ok
